pipeline {
  agent any
  stages {
    stage('demo-stage') {
      steps {
        echo 'echo message from demo stage $DEMO_VAR'
        sh '''
          echo "echo shell message from demo stage shell $BUILD_NUMBER & $DEMO_VAR"
          chmod a+x scripts/init.sh
          ./scripts/init.sh
        '''
      }
    }

  }
  environment {
    DEMO_VAR = '12Aug2022'
  }
}